import odoo

# generate 3 empty variables into local execution space to keep autogenerated content compatiblity
db = None
uid = None
password = None

models = odoo.odooInterface()

# Quick sample:
#
# result = models.execute_kw(db, uid, password, 'product.product', 'search_read',[[]],{'fields': ['id', 'name']})
# for line in result:
#     print(line['name'])

# Search for contacts and retrieve their IDs
contact_ids = models.execute_kw(db, uid, password, 'res.partner', 'search', [[('is_company', '=', False)]])

# Retrieve the contact details based on the IDs
contacts = models.execute_kw(db, uid, password, 'res.partner', 'read', [contact_ids], {'fields': ['name', 'email', 'phone']})

# Print the contacts
for contact in contacts:
    print("Name:", contact['name'])
    print("Email:", contact['email'])
    print("Phone:", contact['phone'])
    print("-----")